# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_forktable.ipynb.

# %% auto 0
__all__ = ['download_data']

# %% ../nbs/05_forktable.ipynb 1
from folktables import ACSDataSource, ACSIncome
from folktables.load_acs import state_list, _STATE_CODES, initialize_and_download
from sklearn.linear_model import LogisticRegression
from sklearn.utils import shuffle
from relax.import_essentials import  *
from fastcore.parallel import parallel
from functools import partial

# %% ../nbs/05_forktable.ipynb 2
def download_data(
    states: List[str] = ["CA"],
    years: List[int] = [2018],
    data_dir: str = "assets/data/acs",
):
    for year in years:
        for state in states:
            data_source = ACSDataSource(
                survey_year=year, horizon='1-Year', survey='person'
            )
            data = data_source.get_data(states=[state], download=True)
            feats, labels, _ = ACSIncome.df_to_pandas(data)
            labels = labels.astype(float)
            feats, labels = shuffle(feats, labels)
            data = pd.concat([feats, labels], axis=1)
            data.to_csv(f"{data_dir}/{year}_{state}.csv", index=False)
            del data

